[[redirects]]
  from = "/"
  to = "/nl/"
  status = 301
  force = false
  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["en","nl"], Country = ["NL"]}
